# PowerShell script to set up GitHub token for Docker builds
# This script helps you configure the GITHUB_TOKEN environment variable

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "GitHub Token Setup for Docker Builds" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if .env file already exists
$envFile = Join-Path $PSScriptRoot ".env"
$envExampleFile = Join-Path $PSScriptRoot ".env.example"

if (Test-Path $envFile) {
    Write-Host "⚠️  .env file already exists!" -ForegroundColor Yellow
    $overwrite = Read-Host "Do you want to overwrite it? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "Setup cancelled." -ForegroundColor Yellow
        exit 0
    }
}

Write-Host ""
Write-Host "To create a GitHub Personal Access Token:" -ForegroundColor Green
Write-Host "1. Go to: https://github.com/settings/tokens" -ForegroundColor White
Write-Host "2. Click 'Generate new token (classic)'" -ForegroundColor White
Write-Host "3. Give it a name (e.g., 'Docker Build Token')" -ForegroundColor White
Write-Host "4. Select the 'read:packages' scope" -ForegroundColor White
Write-Host "5. Click 'Generate token'" -ForegroundColor White
Write-Host "6. Copy the token (you won't see it again!)" -ForegroundColor White
Write-Host ""

$token = Read-Host "Enter your GitHub Personal Access Token"

if ([string]::IsNullOrWhiteSpace($token)) {
    Write-Host "❌ Token cannot be empty!" -ForegroundColor Red
    exit 1
}

# Create .env file
$envContent = @"
# GitHub Personal Access Token for Ep.Platform NuGet Package
# Generated by setup-env.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# 
# IMPORTANT: Never commit this file to git! It's already in .gitignore
GITHUB_TOKEN=$token
"@

try {
    $envContent | Out-File -FilePath $envFile -Encoding utf8 -NoNewline
    Write-Host ""
    Write-Host "✅ .env file created successfully!" -ForegroundColor Green
    Write-Host "   Location: $envFile" -ForegroundColor Gray
    Write-Host ""
    Write-Host "The token will be automatically used by docker-compose." -ForegroundColor Cyan
    Write-Host "You can now run: docker-compose build" -ForegroundColor Cyan
    Write-Host ""
} catch {
    Write-Host "❌ Error creating .env file: $_" -ForegroundColor Red
    exit 1
}








