#!/bin/bash
# Bash script to set up GitHub token for Docker builds
# This script helps you configure the GITHUB_TOKEN environment variable

echo "========================================"
echo "GitHub Token Setup for Docker Builds"
echo "========================================"
echo ""

# Get the directory where the script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ENV_FILE="$SCRIPT_DIR/.env"
ENV_EXAMPLE_FILE="$SCRIPT_DIR/.env.example"

# Check if .env file already exists
if [ -f "$ENV_FILE" ]; then
    echo "⚠️  .env file already exists!"
    read -p "Do you want to overwrite it? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

echo ""
echo "To create a GitHub Personal Access Token:"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token (classic)'"
echo "3. Give it a name (e.g., 'Docker Build Token')"
echo "4. Select the 'read:packages' scope"
echo "5. Click 'Generate token'"
echo "6. Copy the token (you won't see it again!)"
echo ""

read -sp "Enter your GitHub Personal Access Token: " token
echo ""

if [ -z "$token" ]; then
    echo "❌ Token cannot be empty!"
    exit 1
fi

# Create .env file
cat > "$ENV_FILE" << EOF
# GitHub Personal Access Token for Ep.Platform NuGet Package
# Generated by setup-env.sh on $(date '+%Y-%m-%d %H:%M:%S')
# 
# IMPORTANT: Never commit this file to git! It's already in .gitignore
GITHUB_TOKEN=$token
EOF

if [ $? -eq 0 ]; then
    chmod 600 "$ENV_FILE"  # Make it readable only by owner
    echo ""
    echo "✅ .env file created successfully!"
    echo "   Location: $ENV_FILE"
    echo ""
    echo "The token will be automatically used by docker-compose."
    echo "You can now run: docker-compose build"
    echo ""
else
    echo "❌ Error creating .env file"
    exit 1
fi



